# Maching Learning

#### This notebook will clean the data, drop any irrelevant columns, and train a model to predict the time is takes to complete each ticket.

In [26]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

In [15]:
pd.set_option('display.max_columns', None)
df = pd.read_csv("jira_m2_accelerated.csv")

## Data Cleaning

In [16]:
df.drop(columns=["issue_key", "problem_statement", "description", "cause"], inplace=True)

In [17]:
df = df.drop_duplicates()

In [18]:
df

,issue_type,priority_numeric,status,component,story_points,sprint,assignee_id,reporter_id,resolution,num_comments,num_attachments,watchers_count,time_to_resolution_hours,num_transitions,description_length,ticket_age_days,has_labels,parent_epic_id,parent_story_id,has_child_stories,has_child_subtasks,priority,created_date,updated_date
0,Sub-task,5,Code Review,Payment Processing,3,Sprint 17,41,15,Unresolved,7,1,1,41.09,3,28,39,0,NaN,USR-10463,0,0,Highest,2025-09-19,2025-10-17
1,Story,5,Closed,API Services,5,Sprint 14,7,83,Done,5,3,1,71.18,3,37,40,1,WEB-10522,NaN,0,0,Highest,2025-09-18,2025-10-07
2,Bug,3,In Progress,API Services,3,Sprint 6,48,40,Unresolved,5,1,4,45.39,4,27,63,1,NaN,NaN,0,0,Medium,2025-08-26,2025-09-11
3,Epic,4,In Progress,Analytics,1,Sprint 13,91,176,Unresolved,4,1,2,25.08,2,51,9,1,NaN,NaN,1,0,High,2025-10-19,2025-10-28
4,Bug,5,To Do,Payment Processing,5,Sprint 8,102,61,Unresolved,3,0,1,88.71,1,44,69,0,NaN,NaN,0,0,Highest,2025-08-20,2025-09-13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,Task,4,Code Review,API Services,3,Sprint 2,22,50,Unresolved,6,1,1,22.47,2,29,13,1,NaN,NaN,0,0,High,2025-10-15,2025-11-02
1996,Task,3,In Progress,User Management,2,Sprint 4,25,39,Unresolved,6,3,2,104.21,1,15,62,0,NaN,NaN,0,0,Medium,2025-08-27,2025-09-20
1997,Task,1,Closed,Customer Portal,2,Sprint 17,79,80,Done,8,1,1,76.46,3,15,98,1,NaN,NaN,0,0,Lowest,2025-07-22,2025-07-23
1998,Task,2,Code Review,Payment Processing,2,Sprint 20,73,194,Unresolved,5,2,0,94.66,4,61,15,0,NaN,NaN,0,0,Low,2025-10-13,2025-10-22
1999,Story,4,In Progress,Mobile App,1,Sprint 4,69,104,Unresolved,2,0,5,83.02,1,32,92,0,APP-10048,NaN,0,0,High,2025-07-28,2025-08-13

In [19]:
# Encode categorical variables
categorical_cols = ['issue_type', 'status', 'component','sprint', 'resolution', 'parent_epic_id', 'parent_story_id', 'priority']
for col in categorical_cols:
    df[col] = df[col].astype('category').cat.codes

df

,issue_type,priority_numeric,status,component,story_points,sprint,assignee_id,reporter_id,resolution,num_comments,num_attachments,watchers_count,time_to_resolution_hours,num_transitions,description_length,ticket_age_days,has_labels,parent_epic_id,parent_story_id,has_child_stories,has_child_subtasks,priority,created_date,updated_date
0,3,5,2,7,3,9,41,15,1,7,1,1,41.09,3,28,39,0,-1,79,0,0,1,2025-09-19,2025-10-17
1,2,5,1,0,5,6,7,83,0,5,3,1,71.18,3,37,40,1,68,-1,0,0,1,2025-09-18,2025-10-07
2,0,3,4,0,3,17,48,40,1,5,1,4,45.39,4,27,63,1,-1,-1,0,0,4,2025-08-26,2025-09-11
3,1,4,4,1,1,5,91,176,1,4,1,2,25.08,2,51,9,1,-1,-1,1,0,0,2025-10-19,2025-10-28
4,0,5,6,7,5,19,102,61,1,3,0,1,88.71,1,44,69,0,-1,-1,0,0,1,2025-08-20,2025-09-13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,4,4,2,0,3,12,22,50,1,6,1,1,22.47,2,29,13,1,-1,-1,0,0,0,2025-10-15,2025-11-02
1996,4,3,4,9,2,15,25,39,1,6,3,2,104.21,1,15,62,0,-1,-1,0,0,4,2025-08-27,2025-09-20
1997,4,1,1,3,2,9,79,80,0,8,1,1,76.46,3,15,98,1,-1,-1,0,0,3,2025-07-22,2025-07-23
1998,4,2,2,7,2,13,73,194,1,5,2,0,94.66,4,61,15,0,-1,-1,0,0,2,2025-10-13,2025-10-22
1999,2,4,4,5,1,15,69,104,1,2,0,5,83.02,1,32,92,0,13,-1,0,0,0,2025-07-28,2025-08-13

## Target Variable

In [20]:
y = df['time_to_resolution_hours']

X = df.drop(columns=['time_to_resolution_hours'])

## Model

In [25]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [27]:
rf = RandomForestRegressor(
    random_state=42,
  )

In [28]:
rf.fit(X_train, y_train)

# Predictions
y_pred = rf.predict(X_test)

# Evaluation
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

ValueError: could not convert string to float: '2025-10-02'